# Generated by Django 4.0.2 on 2022-09-21 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheepSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheep_sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_contact', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('maximum_selling_price', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('sheep_age', models.IntegerField()),
                ('health_record_book', models.FileField(upload_to='sheep/health_record/')),
                ('sheep_picture', models.ImageField(upload_to='sheep/sheep_pictures/')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sheep_sex_based_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.sheepsex')),
            ],
        ),
    ]
