# Generated by Django 4.0.2 on 2022-09-08 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_types', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CattleSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GoatSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goat_sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ToolPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_purpose', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_contact', models.IntegerField()),
                ('tool_name', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('brief_its_usage', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('tools_number', models.IntegerField()),
                ('maximum_selling_price', models.IntegerField()),
                ('animals_type', models.CharField(blank=True, max_length=500, null=True)),
                ('machinery_tool_picture', models.ImageField(upload_to='machinery/machinery_tools_pictures/')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animaltype')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tool_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.toolpurpose')),
            ],
        ),
        migrations.CreateModel(
            name='Goat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_contact', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('maximum_selling_price', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('goat_age', models.IntegerField()),
                ('health_record_book', models.FileField(upload_to='goat/health_record/')),
                ('goat_picture', models.ImageField(upload_to='goat/goat_pictures/')),
                ('goat_sex_based_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.goatsex')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_contact', models.IntegerField()),
                ('breed', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('selling_price_range', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('cattle_age', models.IntegerField()),
                ('health_record_book', models.FileField(upload_to='cattle/health_record/')),
                ('cattle_picture', models.ImageField(upload_to='cattle/cattle_pictures/')),
                ('cattle_sex_based_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.cattlesex')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
